import {
  LayoutDashboard,
  FolderOpen,
  Layers,
  Tags,
  UploadCloud,
  Search,
  Palette,
  Globe,
  History,
  Users,
  ShieldCheck,
  BarChart3,
  FileText,
  Settings,
  Settings2,
  Link,
  Sliders,
  Webhook,
  Archive,
  LucidePackagePlus,
  LucideMousePointer2,
  Image,
  Film,
  Music,
  File,
  Boxes,
  Share2,
  Lock,
  Workflow,
} from "lucide-react";

export const projectNav = [
  { title: "Overview", icon: LayoutDashboard },
  { title: "Library", icon: FolderOpen },
  { title: "Collections", icon: Layers, badge: "5" },
  { title: "Uploads", icon: UploadCloud },
  { title: "Tags & Metadata", icon: Tags },
  { title: "Search", icon: Search },
  { title: "Brand Templates", icon: Palette },
  { title: "Brand Portal", icon: Globe },
  { title: "Media Types", icon: Image, hasSubmenu: true },
  { title: "Shared With Me", icon: Share2 },
  { title: "Activity Log", icon: History },
  { title: "Team", icon: Users, badge: "7" },
  { title: "Workflows", icon: Workflow },
  { title: "Archive", icon: Archive },
  { title: "Settings", icon: Settings, hasSubmenu: true },
];

export const mediaTypesNav = [
  { title: "Images", icon: Image },
  { title: "Videos", icon: Film },
  { title: "Audio", icon: Music },
  { title: "Documents", icon: FileText },
  { title: "3D Models", icon: Boxes },
  { title: "Raw Files", icon: File },
];

export const settingsNav = [
  { title: "General", icon: Settings2 },
  { title: "Connectivity", icon: Link },
  { title: "Add-ons", icon: LucidePackagePlus },
  { title: "Integrations", icon: Webhook },
  { title: "Usage & Storage", icon: BarChart3 },
  { title: "Permissions", icon: Lock },
  { title: "Advanced", icon: Sliders },
  { title: "Enterprise", icon: LucideMousePointer2 },
];
