CREATE TABLE public.organizations (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name text NULL,
  description text NOT NULL,
  created_by uuid NULL,
  created_at timestamp with time zone NULL,
  owner uuid NULL,
  metadata jsonb NULL,
  is_active boolean NULL DEFAULT false,
  country text NULL,
  phone text NULL,
  CONSTRAINT organizations_pkey PRIMARY KEY (id),
  CONSTRAINT organizations_created_by_fkey
    FOREIGN KEY (created_by) REFERENCES auth.users (id),
  CONSTRAINT organizations_owner_fkey
    FOREIGN KEY (owner) REFERENCES auth.users (id)
) TABLESPACE pg_default;
