// Slide deck for the login screen's right-hand panel. Each entry is one app in
// the suite plus three of its features; the panel shuffles the deck on mount and
// rotates through it, so several slides per app keep the loop from repeating.
import {
  BookOpen,
  Boxes,
  BriefcaseBusiness,
  Building2,
  CalendarCheck,
  CalendarDays,
  ChartNoAxesColumn,
  CheckCircle2,
  Clock4,
  Code2,
  CreditCard,
  FileStack,
  FolderKanban,
  GitBranch,
  Globe,
  Image as ImageIcon,
  Layers,
  Link2,
  ListChecks,
  Mail,
  Megaphone,
  MousePointer2,
  Podcast,
  RadioTower,
  Search,
  Send,
  Share2,
  Shield,
  Sparkles,
  SplitSquareHorizontal,
  Tags,
  Users,
  Wand2,
  Workflow,
  Zap,
} from "lucide-react";

// Per-app accent for the icon tile, kept as whole class strings so Tailwind sees them.
const ACCENTS = {
  flow: "bg-indigo-500/10 text-indigo-400 ring-indigo-500/20",
  notes: "bg-amber-500/10 text-amber-400 ring-amber-500/20",
  assets: "bg-violet-500/10 text-violet-400 ring-violet-500/20",
  grey: "bg-sky-500/10 text-sky-400 ring-sky-500/20",
  office: "bg-teal-500/10 text-teal-400 ring-teal-500/20",
  forms: "bg-emerald-500/10 text-emerald-400 ring-emerald-500/20",
  events: "bg-rose-500/10 text-rose-400 ring-rose-500/20",
  content: "bg-cyan-500/10 text-cyan-400 ring-cyan-500/20",
  campaign: "bg-orange-500/10 text-orange-400 ring-orange-500/20",
  pods: "bg-fuchsia-500/10 text-fuchsia-400 ring-fuchsia-500/20",
  comms: "bg-blue-500/10 text-blue-400 ring-blue-500/20",
  docs: "bg-yellow-500/10 text-yellow-400 ring-yellow-500/20",
  property: "bg-slate-400/10 text-slate-300 ring-slate-400/20",
};

export const SHOWCASE_SLIDES = [
  {
    id: "flow-delivery",
    app: "flow",
    icon: Workflow,
    headline: "Ship work with Geiger Flow",
    blurb: "Issues, sprints, and roadmaps for teams that actually close the loop.",
    features: [
      { icon: ListChecks, label: "Issues, tasks, and sprints" },
      { icon: GitBranch, label: "Branch and PR linking" },
      { icon: ChartNoAxesColumn, label: "Velocity and cycle time" },
    ],
  },
  {
    id: "flow-planning",
    app: "flow",
    icon: FolderKanban,
    headline: "Plan a quarter in an afternoon",
    blurb: "Roadmaps, milestones, and dependencies that stay in step with delivery.",
    features: [
      { icon: CalendarCheck, label: "Milestones and roadmaps" },
      { icon: Users, label: "Workload across the team" },
      { icon: Clock4, label: "Automatic status roll-ups" },
    ],
  },
  {
    id: "notes-knowledge",
    app: "notes",
    icon: FileStack,
    headline: "Write it down in Geiger Notes",
    blurb: "A shared brain for specs, meeting notes, and everything in between.",
    features: [
      { icon: Layers, label: "Nested boards and pages" },
      { icon: Search, label: "Search the whole workspace" },
      { icon: Users, label: "Real-time co-editing" },
    ],
  },
  {
    id: "notes-capture",
    app: "notes",
    icon: Wand2,
    headline: "Capture now, organise later",
    blurb: "Quick capture that files itself onto the right board with the right tags.",
    features: [
      { icon: Zap, label: "Instant quick capture" },
      { icon: Tags, label: "Tags and backlinks" },
      { icon: Share2, label: "Share a page as a link" },
    ],
  },
  {
    id: "assets-dam",
    app: "assets",
    icon: ImageIcon,
    headline: "Every asset in Geiger Assets",
    blurb: "One library for brand files, with versions and approvals built in.",
    features: [
      { icon: Boxes, label: "Versioned asset library" },
      { icon: CheckCircle2, label: "Review and approval flows" },
      { icon: Link2, label: "Expiring share links" },
    ],
  },
  {
    id: "grey-assistant",
    app: "grey",
    icon: Sparkles,
    headline: "Ask Geiger Grey anything",
    blurb: "The assistant that already knows your projects, docs, and decisions.",
    features: [
      { icon: Search, label: "Answers from your work" },
      { icon: Wand2, label: "Drafts, summaries, recaps" },
      { icon: Shield, label: "Scoped to your permissions" },
    ],
  },
  {
    id: "office-ops",
    app: "office",
    icon: BriefcaseBusiness,
    headline: "Run the business in Geiger Office",
    blurb: "People, invoices, and the day-to-day admin nobody wants to chase.",
    features: [
      { icon: Users, label: "Team and HR records" },
      { icon: CreditCard, label: "Invoices and expenses" },
      { icon: Clock4, label: "Time and leave tracking" },
    ],
  },
  {
    id: "forms-intake",
    app: "forms",
    icon: CheckCircle2,
    headline: "Collect answers with Geiger Forms",
    blurb: "Intake, feedback, and surveys that route straight into your projects.",
    features: [
      { icon: MousePointer2, label: "Drag-and-drop builder" },
      { icon: SplitSquareHorizontal, label: "Conditional logic" },
      { icon: Workflow, label: "Responses into Flow" },
    ],
  },
  {
    id: "events-ops",
    app: "events",
    icon: CalendarDays,
    headline: "Run events with Geiger Events",
    blurb: "From the first invite to the door scan, on a single timeline.",
    features: [
      { icon: CalendarCheck, label: "Registration and ticketing" },
      { icon: Users, label: "Attendees and guest lists" },
      { icon: ChartNoAxesColumn, label: "Live sell-through" },
    ],
  },
  {
    id: "content-publishing",
    app: "content",
    icon: Code2,
    headline: "Publish faster with Geiger Content",
    blurb: "Editorial calendars, drafts, and approvals without the spreadsheet.",
    features: [
      { icon: CalendarCheck, label: "Editorial calendar" },
      { icon: CheckCircle2, label: "Review and sign-off" },
      { icon: Globe, label: "Publish to any channel" },
    ],
  },
  {
    id: "campaign-delivery",
    app: "campaign",
    icon: Megaphone,
    headline: "Launch it with Geiger Campaign",
    blurb: "Plan, budget, and measure every campaign from one place.",
    features: [
      { icon: CalendarCheck, label: "Campaign planning" },
      { icon: CreditCard, label: "Budget and spend" },
      { icon: ChartNoAxesColumn, label: "Performance reporting" },
    ],
  },
  {
    id: "pods-audio",
    app: "pods",
    icon: Podcast,
    headline: "Produce shows in Geiger Pods",
    blurb: "Episodes, guests, and distribution handled end to end.",
    features: [
      { icon: ListChecks, label: "Episode pipelines" },
      { icon: Users, label: "Guests and show notes" },
      { icon: Globe, label: "Distribution feeds" },
    ],
  },
  {
    id: "comms-broadcast",
    app: "comms",
    icon: RadioTower,
    headline: "Reach everyone with Geiger Comms",
    blurb: "Announcements and broadcasts that land in the right inboxes.",
    features: [
      { icon: Send, label: "Targeted broadcasts" },
      { icon: Mail, label: "Email and in-app delivery" },
      { icon: ChartNoAxesColumn, label: "Open and reach stats" },
    ],
  },
  {
    id: "docs-published",
    app: "docs",
    icon: BookOpen,
    headline: "Document it with Geiger Docs",
    blurb: "Versioned, searchable documentation you can publish to the world.",
    features: [
      { icon: Layers, label: "Versioned releases" },
      { icon: Search, label: "Instant search" },
      { icon: Globe, label: "Custom domains" },
    ],
  },
  {
    id: "property-portfolio",
    app: "property",
    icon: Building2,
    headline: "Manage estates in Geiger Property",
    blurb: "Portfolios, tenancies, and maintenance tracked against every unit.",
    features: [
      { icon: Boxes, label: "Portfolio and units" },
      { icon: Users, label: "Tenants and leases" },
      { icon: ListChecks, label: "Maintenance requests" },
    ],
  },
  {
    id: "suite-one-login",
    app: "grey",
    icon: Shield,
    headline: "One login for the whole suite",
    blurb: "Sign in once and every Geiger app knows your org, projects, and role.",
    features: [
      { icon: Users, label: "Shared teams and roles" },
      { icon: Shield, label: "SSO for enterprise" },
      { icon: Zap, label: "Switch apps instantly" },
    ],
  },
];

// Accent classes for a slide's icon tile, with a neutral fallback.
export function accentFor(app) {
  return ACCENTS[app] || "bg-surface-strong text-foreground ring-border";
}
